### PR TITLE
Add exclude option

### PR DESCRIPTION
**Pull request by heruka-urgyen**
Hi Mike!
Thanks for this project. I thought it would be useful to allow excluding certain directories in options, so this PR implements it.
### scope
- [x] add exclude option (of type RegExp)
- [x] update readme with exclude option example

### CODE REVIEW

**Comment by mikeerickson** [comment]
@felizbear looks like my comments didnt save.  Here is what I said before marking this PR

This is not necessary, it is already handled by the webpack javascript module loader `exclude` property (see sample below).  

```
var path = require('path')
var TodoWebpackPlugin = require('todo-webpack-plugin');

var webpackConfig = {
  entry:   './index.js',
  output: {
    path: path.join(__dirname, '/dist'),
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {test: /\.js?$/, loaders: [], exclude: /node_modules/},
    ]
  },
  plugins: [
    new TodoWebpackPlugin({
      console:  true,
    })
  ]
};

module.exports = webpackConfig;
```

**Comment by heruka-urgyen** [comment]
@mikeerickson thank you for taking time to respond! The reason I submitted this PR is that upon including this plugin, I saw a list of TODOs from `node_modules`. I use `include` instead of `exclude` in loader definitions, so after reading your comment I tried to use `exclude` instead, but I still see TODOs from `node_modules`. Any idea why it happens?

**Comment by mikeerickson** [comment]
@felizbear if you don't mind, please send me the code for your `webpack.config.js` and I will have a look.  Using the sample I sent you, it performs as expected.

**Comment by heruka-urgyen** [comment]
Hi Mike,

I finally got time to look at it again. It appears, the problem only happens when I'm using webpack-dev-server. Below, I provide a setup that can be used to reproduce it.

```
/*** package.json ***/

{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node dev-server.js"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "todo-webpack-plugin": "^1.2.0",
    "webpack": "^1.13.2",
    "webpack-dev-server": "^1.16.1"
  }
}

/*** dev-server.js ***/

var config = require("./webpack.config.js")
var webpack = require("webpack")
var WebpackDevServer = require("webpack-dev-server")

var devPort = "9090"
var devHost = "localhost"
var devUrl  = "http://" + devHost + ":" + devPort
var builder = webpack(config(devUrl))

new WebpackDevServer(builder, {
  publicPath: devUrl,
  stats: {
    assets: false,
    colors: true,
    version: false,
    hash: false,
    timings: false,
    chunks: false,
    chunkModules: false
  }
}).listen(devPort, devHost, function(err, result) {
  if (err) {
    console.log(err)
  }

  console.log("Webpack server is listening at " + devUrl)
})

/*** webpack.config.js ***/

var TodoWebpackPlugin = require("todo-webpack-plugin")

module.exports = function(publicPath) {
  return {
    entry: [
      "webpack-dev-server/client?" + publicPath,
      "webpack/hot/only-dev-server",
      "./index.js"
    ],
    output: {
      path: "/",
      publicPath,
    },
    module: {
      loaders: [
        {test: /\.js?$/, loaders: [], exclude: /node_modules/},
      ]
    },
    plugins: [
      new TodoWebpackPlugin({
        console:  true,
      })
    ]
  }
}
```

`npm i && npm start` and you should be able to see lots of TODOs from node_modules in your terminal

**Comment by mikeerickson** [comment]
@felizbear thx for digging deeper, I will have a closer look over the weekend.

**Pull request closed without merging**
